---
title: "Assignment"
author: "ThetLwinLwin"
date: "1/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## No of People older than 60 in Myanmar

Loading libraries and  the geojson data of myanmar.
```{r,message FALSE,warning=FALSE}
library(leaflet)
library(dbplyr)
library(rgdal)
library(spdplyr)

myanmar <- readOGR('myanmar.geojson')
```

Reading data from **union_myan_group_a.xlsx** and merge to Spatialpolygon-Dataframe. 
Then select only necessary data.

```{r, message=FALSE,warning=FALSE}
myanmar$total <- c(206515,203481,17179,569906,109051,83747,424498,645329,405631,495140,580359,35796,122317,102612,472847)
myanmar_select <- myanmar%>% select(id_1,name,total)
```

Convert the data to color numeric and forming labels.

```{r, message=FALSE,warning=FALSE}
pal <- colorNumeric('Reds',domain = myanmar_select$total)
labels <- sprintf(
  "<strong>%s</strong><br/>%s people",
  myanmar_select$name, myanmar_select$total
) %>% lapply(htmltools::HTML)
```

Making Graph

```{r, message=FALSE,warning=FALSE}
leaflet(myanmar_select) %>%
  addProviderTiles("MapBox",options = providerTileOptions(
    id = "mapbox.light",
    accessToken = 'pk....'
  )) %>%
  addPolygons(
    fillColor = ~pal(total),
    weight = 1,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 2,
      color = "#a9bad4",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE
    ),
    label = labels,
    labelOptions = labelOptions(
      style = list( "font-weight" = "normal",
                    padding = "3px 8px",
                    "box-shadow" = "3px 3px rgba(0,0,0,0.25)",
                    "border-color" = "rgba(0,0,0,0.8)"),
      textsize = "15px",
      direction = "auto"
    )
  )%>%
  addLegend(pal = pal, 
            values = ~total,
            title = 'No of People older than 60',
            position = 'bottomright')
```

**REPLACE YOUR OWN API KEY**

